# Generated by Django 4.2.5 on 2023-10-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_artist_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
